version: '3'

dotenv: ['.env']

env:
  TITLE: eShop On AKS
  SKU: "Standard_D4ads_v5"
  COUNT: 2
  DOMAIN_ROOT: "bjdazure.tech"

tasks:
  default: 
    cmds: 
    - task --list 
  
  up:
    desc: Creates Azure infrastructure and deploys application code
    cmds:
    - terraform -chdir=./infrastructure workspace new {{.REGION}} || true
    - terraform -chdir=./infrastructure workspace select {{.REGION}}
    - terraform -chdir=./infrastructure init
    - task: apply
    - task: creds
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  apply:
    cmds:
    - terraform -chdir=./infrastructure apply -auto-approve
       -var "region={{.REGION}}" 
       -var "vm_size={{.SKU}}" 
       -var "node_count={{.COUNT}}"
       -var "tags={{.TITLE}}" 
       -compact-warnings
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  refresh:
    cmds:
    - terraform -chdir=./infrastructure refresh 
      -var "region={{.REGION}}" 
      -var "vm_size={{.SKU}}" 
      -var "node_count={{.COUNT}}" 
      -var "tags={{.TITLE}}"
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  creds:
    desc: Gets credential file for newly created AKS cluster
    cmds:
    - az aks get-credentials -g {{.RG}} -n {{.AKS}} --overwrite-existing
    - kubelogin convert-kubeconfig -l azurecli
    vars:
      RG: 
        sh: terraform -chdir=./infrastructure output -raw RESOURCE_GROUP
      AKS: 
        sh: terraform -chdir=./infrastructure output -raw AKS_CLUSTER_NAME

  configs:
    desc: Update configurations with proper values Key
    cmds:
    - helm upgrade --install eshop-k8s-extensions
      --set APP_NAME={{.APP_NAME}} 
      --set WEBAPP_DOMAIN={{.WEBAPP_DOMAIN}} 
      --set APP_INSIGHTS.CONNECTION_STRING="{{.AI_CONNECTION_STRING}}"
      ./charts/eshop-k8s-extensions 
    vars:
      APP_NAME:
        sh: terraform -chdir=./infrastructure output -raw APP_NAME
      AI_CONNECTION_STRING:
        sh: terraform -chdir=./infrastructure output -raw AI_CONNECTION_STRING
      WEBAPP_DOMAIN: '{{.APP_NAME}}.{{.DOMAIN_ROOT}}'
      
  build: 
    desc: Builds containers
    dir: ./scripts
    cmds:
    - pwsh ./build_containers.ps1 -AppName {{.APP_NAME}} -SubscriptionName {{.SUBSCRIPTION_NAME}} -SourceRootDirectory {{.SOURCE_DIR}} -verbose
    vars:
      APP_NAME: 
        sh: terraform -chdir=../infrastructure output -raw APP_NAME
      SUBSCRIPTION_NAME:
        sh: az account show --query name -o tsv
      SOURCE_DIR: '{{default "~/code/eShop" .CLI_ARGS}}'

  deploy:
    desc: Deploys application via Helm
    dir: ./scripts
    cmds:
    - pwsh ./deploy_services.ps1 -AppName {{.APP_NAME}} -SubscriptionName {{.SUBSCRIPTION_NAME}} -Domain {{.DOMAIN_ROOT}} -verbose
    vars:
      APP_NAME: 
        sh: terraform -chdir=../infrastructure output -raw APP_NAME
      SUBSCRIPTION_NAME:
        sh: az account show --query name -o tsv        

  update-firewalls:
    desc: Update firewall rules for Keyvault, AKS, and ACR
    dir: ./scripts
    cmds:
    - bash ./scripts/update-firewalls.sh

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="{{.TITLE}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --no-wait -n || true
    - cd infrastructure ;
      rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true
