kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: catalog
data:
  Identity__Url: http://identity-api
  AZURE_CLIENT_ID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalog
  template:
    metadata:
      labels:
        app: eshop
        service: catalog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"        
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}  
      containers:
        - name: catalog-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/catalog-api:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: catalog-cm
          env:
          - name: ConnectionStrings__catalogdb
            valueFrom:
              secretKeyRef:
                name: catalogdb-connection-string
                key: catalogdb-connection-string
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "eshop-secrets"             
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: catalog-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: catalog
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: HTTP
  selector:
    service: catalog
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  catalog-api-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  -  {{ .Values.ISTIO.HOST }}
  gateways:
  -  {{ .Values.ISTIO.GATEWAY }}
  http:
  - route:
    - destination:
        host: catalog-api
        port:
          number: 8080