kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog-cm
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: catalog-api
data:
  Identity__Url: {{ .Values.ISTIO.IDENTITY.INTERNAL_URL }}
  AZURE_CLIENT_ID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"  
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalog-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: catalog-api
        azure.workload.identity/use: "true"         
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"        
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}  
      containers:
        - name: catalog-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/catalog-api:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: {{ .Values.ISTIO.CATALOG.PORT }}     
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false          
          # livenessProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: {{ .Values.ISTIO.CATALOG.PORT }}
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   timeoutSeconds: 3
          # startupProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: {{ .Values.ISTIO.CATALOG.PORT }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 3       
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"                       
            readOnly: true               
          envFrom:
            - configMapRef:
                name: catalog-cm
          env:
          - name: ConnectionStrings__eventbus
            valueFrom:
              secretKeyRef:
                name: eventbus-secret
                key:  RABBITMQ_CONNECTION_STRING           
          - name: ConnectionStrings__catalogdb
            valueFrom:
              secretKeyRef:
                name: eshop-kv-secrets
                key: catalogdb-connection-string
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: eshop-secrets              
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: catalog-api
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: catalog-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ISTIO.CATALOG.PORT }}
  selector:
    service: catalog-api