kind: ConfigMap
apiVersion: v1
metadata:
  name: identity-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity
data:
  AZURE_CLIENT_ID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  BasketApiClient: http://basket-api
  OrderingApiClient: http://ordering-api
  WebAppClient: http://webapp
  WebhooksApiClient: http://webhooks-api
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity-api
  template:
    metadata:
      labels:
        app: eshop
        service: identity-api
      annotations:
        dapr.io/log-as-json: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"        
    spec:
      containers:
        - name: identity-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/identity-api:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: identity-cm
          env:
          - name: ConnectionStrings__identitydb
            valueFrom:
              secretKeyRef:
                name: identitydb-connection-string
                key: identitydb-connection-string
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "eshop-secrets"                
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: identity-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: HTTP
  selector:
    service: identity
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  identity-api-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  -  {{ .Values.ISTIO.HOST }}
  gateways:
  -  {{ .Values.ISTIO.GATEWAY }}
  http:
  - route:
    - destination:
        host: identity-api
        port:
          number: 8080