apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.NAMESPACE }}
  labels:
    istio.io/rev: asm-1-20
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "ReservedFor", "operator": "Equal", "effect": "NoSchedule", "value": "apps"}]'