kind: ConfigMap
apiVersion: v1
metadata:
  name: payment-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: payment-processor
data:
  Identity__Url: http://identity-api
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-processor
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: payment-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment-processor
  template:
    metadata:
      labels:
        app: eshop
        service: payment-processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"        
    spec:
      containers:
        - name: payment-processor
          image: {{ print .Values.ACR.NAME ".azurecr.io/orderprocessor:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: payment-cm
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: payment-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: HTTP
  selector:
    service: payment-api
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  payment-api-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  -  {{ .Values.ISTIO.HOST }}
  gateways:
  -  {{ .Values.ISTIO.GATEWAY }}
  http:
  - route:
    - destination:
        host: payment-api
        port:
          number: 8080