kind: ConfigMap
apiVersion: v1
metadata:
  name: payment-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: payment-api
data:
  Identity__Url: {{ .Values.ISTIO.IDENTITY.INTERNAL_URL }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"  
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: payment-api
        azure.workload.identity/use: "true"         
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"        
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      containers:
        - name: payment-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/orderprocessor:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: {{ .Values.ISTIO.PAYMENT.PORT }}
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false          
          # livenessProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: {{ .Values.ISTIO.PAYMENT.PORT }}
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   timeoutSeconds: 3
          # startupProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: {{ .Values.ISTIO.PAYMENT.PORT }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 3       
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"                       
            readOnly: true
          envFrom:
            - configMapRef:
                name: payment-cm
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: eshop-secrets          
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: payment-api
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ISTIO.PAYMENT.PORT }}
    targetPort: {{ .Values.ISTIO.PAYMENT.PORT }}
  selector:
    service: payment-api