apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: eshop-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.KEYVAULT.NAME }}
    clientID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
    cloudName: ""                                         
    objects:  |
      array:
        - |
          objectName: catalogdb-connection-string
          objectType: secret
          objectVersion: ""         
        - |
          objectName: identitydb-connection-string
          objectType: secret
          objectVersion: ""     
        - |
          objectName: orderingdb-connection-string
          objectType: secret
          objectVersion: ""     
        - |
          objectName: webhooksdb-connection-string
          objectType: secret
          objectVersion: ""     
        - |
          objectName: redis-connection-string
          objectType: secret
          objectVersion: ""                               
    tenantId: {{ .Values.WORKLOAD_ID.TENANT_ID }}