kind: ConfigMap
apiVersion: v1
metadata:
  name: webhooks-api-cm
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: webhooks-api
data:
  AZURE_CLIENT_ID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
  #Identity__Url: {{ .Values.ISTIO.IDENTITY.INTERNAL_URL }}
  Identity__Url: {{ print "https://" .Values.ISTIO.IDENTITY.EXTERNAL_URL }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.OTEL.ENDPOINT }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webhooks-api
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: webhooks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webhooks-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: webhooks-api
        azure.workload.identity/use: "true" 
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ISTIO.WEBHOOKS.PORT | quote }}
        prometheus.io/path: "/metrics"             
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      containers:
        - name: webhooks-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/webhooks-api:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.ISTIO.WEBHOOKS.PORT }}
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false          
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: {{ .Values.ISTIO.WEBHOOKS.PORT }}
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   timeoutSeconds: 3   
          envFrom:
            - configMapRef:
                name: webhooks-api-cm
          env:
          - name: ConnectionStrings__webhooksdb
            valueFrom:
              secretKeyRef:
                name: eshop-kv-secrets
                key: webhooksdb-connection-string                 
          - name: ConnectionStrings__eventbus
            valueFrom:
              secretKeyRef:
                name: eventbus-secret
                key:  RABBITMQ_CONNECTION_STRING
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: eshop-secrets                              
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: webhooks-api
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ISTIO.WEBHOOKS.PORT }}
  selector:
    service: webhooks-api