apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: aks-istio-ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.CERT.EMAIL_ADDRESS | quote }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.WEBAPP_DOMAIN | replace "." "-" }}
  namespace: aks-istio-ingress
spec:
  secretName: istio-ingress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - {{ print "eshop." .Values.WEBAPP_DOMAIN | quote }}
  - {{ print "shop." .Values.WEBAPP_DOMAIN | quote }}
  - {{ print "identity." .Values.WEBAPP_DOMAIN | quote }}
  - {{ print "basket." .Values.WEBAPP_DOMAIN | quote }}