apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: aks-istio-ingress
spec:
  selector:
    istio: aks-istio-ingressgateway-external  
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ print "*." .Values.WEBAPP_DOMAIN | quote }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingress-tls
    hosts:
    - {{ print "*." .Values.WEBAPP_DOMAIN | quote }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  default-virtualservice
  namespace: aks-istio-ingress
spec:
  hosts:
  -  {{ print "*." .Values.WEBAPP_DOMAIN | quote }}
  gateways:
  -  aks-istio-ingress/istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: {{ print "/.well-known/acme-challenge/" .VALUES.CERT.WEBAPP_CHALLENGE | quote }}
    route:
    - destination:
        host: {{ print "cm-acme-http-solver-" .VALUES.CERT.WEBAPP_SERVICE }}
        port:
          number: 8089
  - match:
    - uri:
        prefix: {{ print "/.well-known/acme-challenge/" .VALUES.CERT.IDENTITY_CHALLENGE | quote }}
    route:
    - destination:
        host: {{ print "cm-acme-http-solver-" .VALUES.CERT.IDENTITY_SERVICE }}
        port:
          number: 8089          
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: default-backend-svc
        port:
          number: 80