kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: webapp
    namespace: {{ .Values.NAMESPACE }}
spec:
    hosts:
    - {{ .Values.ISTIO.WEBAPP.EXTERNAL_URL }}
    scaleTargetRef:
        name: webapp
        kind: Deployment
        apiVersion: apps/v1
        service: webapp
        port: {{ .Values.ISTIO.WEBAPP.PORT }}
    replicas:
        min: 1
        max: 5