name: Playwright Tests for eShop
on:
  workflow_dispatch:
    inputs:
      eshop_url:
        description: 'The URL for eShop'
        required: true
        default: 'https://shop.contoso.com'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APPLICATION_URI: ${{ github.event.inputs.eshop_url }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium
    - name: Run Playwright tests
      run: npx playwright test
      env:
        USERNAME1: bob
        PASSWORD: Pass123$
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
